config/routes.rb
Rails.application.routes.draw do
  devise_for :drivers
 root to: "bookings#new"
  devise_for :users

  scope :user do
  	resource :bookings, only: [:show,:new,:create] do 
  		collection do
  		 get "mark_complete"
  		 post "completed"
  		 get 'start'
  		 post 'started'
  		end
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :booking_status
  belongs_to :user
  belongs_to :driver
  belongs_to :vehicle
  has_one :drop_location
  DEFAULT_DISTANCE = 5
  attr_accessor :start_address, :end_address
end

app/models/booking_status.rb
class BookingStatus < ApplicationRecord
	has_many :bookings
end

app/models/driver.rb
class Driver < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :vehicles   

  geocoded_by :address, :latitude  => :lat, :longitude => :lng
   

   def active_vehicle
   		vehicles.find_by(active: true)
   end

end

app/models/drop_location.rb
class DropLocation < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :user_addresses
         has_many :bookings
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :driver
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	before_action :authenticate_user!, only: [:create]
	DEFAULT_DISTANCE = 5
	def new
		@booking = Booking.new
	end

	def create
		@booking = current_user.bookings.new
		seat_request = params[:booking][:no_of_passenger]
		@drivers = Driver.where("free_seats >= ? AND active = ?",seat_request, true)
			@message = 	find_driver_near_me
			flash[:notice] = @message
		redirect_to bookings_path	
	end

	def show
		
	end

	def start
		
	end

	def started
		@booking = Booking.find_by(id: params[:booking][:id])
		if @booking.nil?
			flash[:alert] = "Booking not found"
		elsif @booking.booking_status.default_name == "accepted"
			st_id = BookingStatus.find_by(default_name: 'started').id
			@booking.update(booking_status_id: st_id)
			flash[:notice] = "Booking started"
		else
			flash[:alert] = "Invalid booking"
		end
		redirect_to bookings_path
	end

	def mark_complete
		
	end


	def completed
		@booking = Booking.find_by(id: params[:booking][:id])
		if @booking.nil?
			flash[:alert] = "Booking not found"
		elsif @booking.booking_status.default_name == "started"
		st_id = BookingStatus.find_by(default_name: 'completed').id
		@booking.update(booking_status_id: st_id)
		driver = @booking.driver
		driver.update(:free_seats=> driver.free_seats+@booking.no_of_passenger)
		flash[:notice] = "Booking completed"
	else
		flash[:alert] = "Invalid booking"
		end
		redirect_to bookings_path
	end

	def find_driver_near_me
		start_lat_lng = [30.7185, 76.7144]
		end_lat_lng = [30.7184, 76.7145]
		driver  =	@drivers.near(start_lat_lng,DEFAULT_DISTANCE).sample
		if driver.present?
			booking_initialize(driver)
			message = "booking successfuly created"
		else
			message = "No driver near you"
		end
	end


	def booking_initialize(driver)
			@booking.driver_id = driver.id
			@booking.vehicle_id = driver.active_vehicle.try(:id)
			@booking.booking_status_id = BookingStatus.find_by(default_name: 'accepted').id
			@booking.no_of_passenger = params[:booking][:no_of_passenger]
			@booking.pickup_location = params[:booking][:start_address]
			@booking.lat = 30.7185
			@booking.lng = 76.7144
			@booking.build_drop_location(address: params[:booking][:end_address],lat: 30.7184, lng: 76.7145)
			@booking.save!
			driver.free_seats -= @booking.no_of_passenger
			driver.save!
	end

	

	private



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/mark_complete.html.erb
<div class="container">
	<h4> Booking Complete</h4>
<%= form_for :booking, url: completed_bookings_path do |f| %>
  Booking ID <%= f.text_field :id, required: true %><br /><br />
  <%= f.submit "Booking Complete"%>
<% end %>
</div>

app/views/bookings/new.html.erb
<div class="container">
	<%= link_to "Complete OnGoing Booking", mark_complete_bookings_path %><br/>
	<%= link_to "Start Accepted Booking", start_bookings_path %>
	<h4>Create Booking Request</h4>
<%= form_for @booking do |f| %>
<div class="form-group">
  pickup address: <%= f.text_field :start_address, required: true %>
</div>
<div class="form-group">
  drop address : <%= f.text_field :end_address, required: true %>
</div>
  Seat : <%= f.select :no_of_passenger, [1,2] %><br /><br />
  <%= f.submit "Booking Request"%>
<% end %>
</div>

app/views/bookings/show.html.erb
<%= @message %>
<%= link_to "Booking Page", new_bookings_path%>

app/views/bookings/start.html.erb
<div class="container">
	<h4> Booking Start</h4>
<%= form_for :booking, url: started_bookings_path do |f| %>
  Booking ID <%= f.text_field :id, required: true %><br /><br />
  <%= f.submit "Booking Start"%>
<% end %>
</div>

<%= link_to "Booking Page", new_bookings_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>